### ISSUE TITLE
Port to Python3.x

### ISSUE THREAD

**Issue by elbeejay** [isikdogan/rivamap#2]
Wanted to combine this code with some other packages so I made the minor edits to port it to Python3.7. They are available on my fork of rivamap here: https://github.com/elbeejay/rivamap

Did not want to pull request this original codebase as I was not sure how this is normally handled, but wanted to let you know.

- Jay

**Comment by isikdogan** [comment]
Thanks for your contribution. Feel free to send a pull request.

**Comment by joemcglinchy** [comment]
just wanted to re-open this briefly. I installed the package via pip but the print statement in `singularity_index` was not updated to python 3.x syntax (`print(...)` vs `print ...`), although i see it updated in the codebase here. Easy enough fix, but may want to consider fixing it for the pip build.
