### ISSUE TITLE
error in import singularity_index

### ISSUE THREAD

**Issue by unaschneck** [isikdogan/rivamap#9]
When trying to import singularity_index as

`from rivamap import singularity_index`

This error happens

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/rivamap/singularity_index.py", line 110
    print "Processing scale: " + str(s)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
```

**Comment by elbeejay** [comment]
Hi @unaschneck

If you installed via PyPi (`pip install rivamap`) then it will definitely not work on any recent Python version as the version hosted on PyPi is compatible with Python 2.7 but will not work for any Python 3.x.

Best way to get a working copy of the code is to install from the source code in the repository which was updated to be compatible with Python 3.

**Comment by unaschneck** [comment]
Great, thanks!

**Comment by unaschneck** [comment]
great, thank you
